### ISSUE TITLE
运行过程遇到一些问题

### ISSUE THREAD

**Issue by szh91** [hou-yz/open-reid-tracking#11]
我想用PCB在mark1501上训练，我数据集路径是./Data/Market-1501-v15.09.15,
然后运行 CUDA_VISIBLE_DEVICES=0 python3 PCB.py -d ./Data/Market-1501-v15.09.15 --train
出现这样错误：

PCB.py: error: argument -d/--dataset: invalid choice: './Data/Market-1501-v15.09.15' (choose from 'aic_reid', 'aic_tracking', 'duke_reid', 'duke_tracking', 'market1501', 'veri')

**Comment by hou-yz** [comment]
thanks for your feedback.
please fetch the latest update https://github.com/hou-yz/open-reid-tracking/commit/7a40462231e27e607dd094412550f26270b4efb8 for fixes.
please try to specify your dataset argument as ```-d market1501``` and the dataset directory argument as ```--data-dir ./Data```. 
otherwise, you can also modify the dataset file to change the default dataset folder from ~/Data/Market-1501-v15.09.15 to whatever suits your mind in https://github.com/hou-yz/open-reid-tracking/blob/7a40462231e27e607dd094412550f26270b4efb8/reid/datasets/market1501.py#L10.
